const http=require('http'),fs=require('fs');
const port=process.env.PORT||10000;
const BASE_URL=process.env.BASE_URL||'https://monopoly-command-center-v67.floot.app/_cdn/static/f4ebb851-c03c-451c-81c5-343be9983db0-command-center-v67-all3-currentmodel.txt';
const patch=[fs.readFileSync('game-detail-ui-patch.html','utf8'),fs.readFileSync('mobile-patch.html','utf8'),fs.readFileSync('mobile-nav-fix.html','utf8'),fs.readFileSync('week4-sportsline-integration-patch.html','utf8'),fs.readFileSync('week4-overview-page.html','utf8'),fs.readFileSync('five-factor-scorecard-page.html','utf8'),fs.readFileSync('ats-trends-v2-ui-patch.html','utf8')].join('\n');
const current=JSON.parse(fs.readFileSync('week4-current-data.json','utf8'));
const sl=JSON.parse(fs.readFileSync('week4-sportsline-2026-10-03-1611ET.json','utf8'));
const ga=JSON.parse(fs.readFileSync('week4-gridiron-2026-10-03.json','utf8'));
const nf=JSON.parse(fs.readFileSync('week4-nfelo-2026-10-03-1720ET.json','utf8'));
const live=JSON.parse(fs.readFileSync('week4-live-market-context-2026-10-03-1710ET.json','utf8'));
const opt=JSON.parse(fs.readFileSync('v2/results/week_04_nfelo_optimizer_rerun_2026-10-03.json','utf8'));
const atsV2=JSON.parse(fs.readFileSync('ats-trends-v2-week04-results.json','utf8'));
const atsLedger=JSON.parse(fs.readFileSync('ats-trends-prospective-ledger.json','utf8'));
const ffEngine=require('./five-factor-scorecard-engine');
const ffInput=JSON.parse(fs.readFileSync('five-factor-scorecard-data-week04.json','utf8'));
const ff=ffEngine.scoreSlate(ffInput);
current.version='week4-native-v9-five-factor-atsv2-2026-10-03';current.captured_at_local=nf.captured_at_local;current.snapshot_label='Week 4 Saturday · Oct 3 · ATS Trends v2 challenger visible alongside locked v1';
const by=Object.fromEntries(current.games.map(g=>[g.game,g]));
const s=n=>n>0?`+${n}`:`${n}`,gg=p=>p>=55?'A':p>=52?'B':p>=51?'C':'N';
function gb(d){if(d.away_cover_pct===d.home_cover_pct)return{side:'NO TAKE',pct:50};return d.away_cover_pct>d.home_cover_pct?{side:d.away,pct:d.away_cover_pct}:{side:d.home,pct:d.home_cover_pct};}
function nb(d){const a={side:d.away,ev:d.ev_away_pct,cur:d.current_away,mod:d.model_away},h={side:d.home,ev:d.ev_home_pct,cur:d.current_home,mod:d.model_home};return a.ev>=h.ev?a:h;}
for(const g of current.games){const a=sl.games[g.game],b=ga.games[g.game],c=nf.games[g.game],d=live.games[g.game];if(!a||!b||!c||!d)throw Error('missing '+g.game);const x=gb(b),y=nb(c);g.current=d.action_spread;g.weather=d.weather;g.marketNote=d.market_note;g.sportsline={grade:a.sim_grade,currentPrice:a.current_spread,openPrice:a.open_spread,visiblePick:a.sim_pick,kind:a.sim_type,pickCount:a.sportsline_pick_count,moneyPct:a.money_pct,simPct:a.sim_pct,projectedScore:Object.entries(a.projected).map(([t,p])=>`${t} ${p}`).join(' · ')};g.gridiron={line:`${b.home} ${s(b.home_spread)}`,away:b.away,awayPct:b.away_cover_pct,home:b.home,homePct:b.home_cover_pct,bestSide:x.side,bestPct:x.pct,grade:gg(x.pct)};g.nfelo={away:c.away,home:c.home,currentAway:c.current_away,currentHome:c.current_home,modelAway:c.model_away,modelHome:c.model_home,evAway:c.ev_away_pct,evHome:c.ev_home_pct,bestSide:y.side,bestEv:y.ev,bestCurrent:y.cur,bestModel:y.mod,positiveEdge:y.ev>0};g.news=[{detail:d.injuries}];g.sources={sportsline:g.sportsline,gridiron:g.gridiron,nfelo:g.nfelo};}
const D={
'DEN @ SF':['High','Core key-number price value','Best current Sly key-number advantage; nfelo neutral.','External spread models do not independently confirm Denver.'],
'KC @ LV':['Medium+','Exact-line cross-model alignment','SportsLine B + Gridiron A/57% align exactly on KC -4.5.','No market price edge; nfelo is neutral.'],
'LAR @ PHI':['Medium+','nfelo model-gap value with injury cap','nfelo PHI +3.5 vs +2.5 model, +14% displayed EV; Sly keeps hook through 3.','Substantial Philadelphia injuries cap exposure.'],
'ARI @ NYG':['Medium+','Cross-model dog value','Gridiron likes NYG at +1.5 and nfelo models +0.5 vs current +2.5.','SportsLine is total-only here.'],
'LAC @ SEA':['Medium+','SportsLine football-model core','SportsLine B and ≈60% public cover support at SEA -7.','No price edge; Gridiron/nfelo neutral.'],
'IND @ WAS':['Medium','SportsLine price + injury context','Sly -3.5 is one point better than SportsLine plus Washington QB/OL absences.','Action/nfelo are neutral at -3.5.'],
'DET @ CAR':['Conflict','nfelo contradiction watch','nfelo CAR +3 vs +3.5 and +5.9% EV make Carolina a real watch.','Gridiron leans DET 51%.'],
'TEN @ BAL':['Low-Med','Gridiron exact-line watch','Gridiron TEN 52% at +11.5.','Only one spread-model signal.'],
'JAX @ CIN':['Conflict','External-model disagreement','SportsLine B supports JAX +2.5.','Gridiron leans CIN 51%; nfelo neutral.'],
'GB @ TB':['Low','Underdog directional watch','Gridiron 51% TB plus SportsLine TB moneyline direction.','SportsLine is not ATS; QB context adverse.'],
'NE @ BUF':['Low-Med','Key-number value with injury conflict','Sly +7 beats Action +6.5.','Gridiron BUF 51% and injuries argue against NE.'],
'ATL @ NO':['Low','Weak external support','SportsLine C and Gridiron direction support ATL.','Gridiron probability is at +3, not Sly +2.5.'],
'DAL @ HOU':['Conflict','Direct source conflict','Gridiron prefers DAL while SportsLine backs HOU.','No clean side.'],
'MIA @ MIN':['Line penalty','Strong model at worse contest price','Gridiron likes MIN -10.5.','SportsLine A is only at -9.5; Jefferson out.'],
'NYJ @ CHI':['Mixed','Market-equal injury conflict','Gridiron CHI 52% only.','No price edge; injuries messy.']};
for(const r of opt.ranking){const g=by[r.game],[confidence,role,whyPlay,against]=D[r.game];Object.assign(g,{rank:r.rank,state:r.decision,decision:r.decision,lean:r.pick,confidence,role,whyPlay,against,evidence:r.reason,catherine:0,amanda:0});}
for(const w of opt.portfolio.Catherine){const g=current.games.find(x=>x.lean===w.pick);if(g)g.catherine=w.amount;}for(const w of opt.portfolio.Amanda){const g=current.games.find(x=>x.lean===w.pick);if(g)g.amanda=w.amount;}
current.games.sort((a,b)=>a.rank-b.rank);current.working_portfolio={...opt.portfolio,status:'SATURDAY_NFELO_RERUN_NOT_SUBMISSION_FINAL'};
const mainSide=Object.fromEntries(current.games.map(g=>[g.game,g.lean==='NO TAKE'?null:(g.lean||'').split(' ')[0]]));
for(const g of ff.games){const o=g.fiveFactor.overall,m=mainSide[g.game];g.mainSystemComparison={mainSide:m,status:!m?'MAIN SYSTEM NO TAKE':o.leanSide==='neutral'?'FIVE-FACTOR NO EDGE':o.lean===m?'AGREES':'DISAGREES'};}
ff.review={status:'ADVERSARIAL_REVIEWED_WITH_CAVEATS',reviewedAt:'2026-10-03T20:40:00-04:00',moneySemantics:'DraftKings Spread % Handle only; Bets % excluded',defenseCutoff:'Week 4 pregame snapshot; Sunday/Monday teams have three completed games; refresh before PRE_KICK_FINAL',correlation:'Line movement and handle can be correlated; separate equal-weight challenger factors in v1.0',atsTrends:'v1 remains locked official Week 4 factor; v2 is preferred challenger shown side-by-side and tracked prospectively'};
const grades={1:'A',2:'A-',3:'A-',4:'B+',5:'B+',6:'B',7:'C+',8:'C+',9:'C',10:'C',11:'C-',12:'C-',13:'—',14:'—',15:'—'};
current.sourceData=current.games.map(g=>{const a=g.sportsline,b=g.gridiron,c=g.nfelo;return{game:g.game,time:g.time,sly:g.sly,current:g.current,ourGrade:grades[g.rank],ourPick:g.lean,ourState:g.decision,ourRank:g.rank,sportsGrade:a.grade,sportsPick:a.visiblePick,sportsType:a.kind,sportsCurrent:a.currentPrice,sportsMoney:Object.entries(a.moneyPct||{}).map(([t,p])=>`${t} ${p}%`).join(' · '),sportsSimPct:a.simPct?`${a.simPct.cover_pct}% ${a.simPct.team}`:'not publicly exposed',gridGrade:b.grade,gridPick:b.bestSide==='NO TAKE'?'50/50':`${b.bestSide} ${b.bestPct}%`,gridLine:b.line,gridOther:`${b.away} ${b.awayPct}% / ${b.home} ${b.homePct}%`,nfeloBest:c.positiveEdge?`${c.bestSide} ${s(c.bestCurrent)} · model ${s(c.bestModel)} · EV ${s(c.bestEv)}%`:'Neutral',lucas:'UNVERIFIED / NOT SUPPLIED',agreement:g.evidence};});
function replaceArray(html,name,value){const n=`const ${name}=`,d=html.indexOf(n),start=html.indexOf('[',d+n.length);let dep=0,q=null,e=false,end=-1;for(let i=start;i<html.length;i++){const ch=html[i];if(q){if(e)e=false;else if(ch==='\\')e=true;else if(ch===q)q=null;continue;}if(ch==='"'||ch==="'"||ch==='`'){q=ch;continue;}if(ch==='[')dep++;else if(ch===']'&&--dep===0){end=i+1;break;}}return html.slice(0,start)+JSON.stringify(value)+html.slice(end);}
let cache=null;async function app(){if(cache)return cache;let html=await(await fetch(BASE_URL)).text();html=replaceArray(html,'games',current.games);html=replaceArray(html,'sourceData',current.sourceData);const st=`<script>window.WEEK4_CURRENT_META=${JSON.stringify({version:current.version,captured_at_local:current.captured_at_local,snapshot_label:current.snapshot_label,balances:current.balances,working_portfolio:current.working_portfolio})};window.WEEK4_CURRENT_PUBLIC=${JSON.stringify(current.games)};window.WEEK4_SOURCE_PUBLIC=${JSON.stringify(current.sourceData)};window.FIVE_FACTOR_PUBLIC=${JSON.stringify(ff)};window.ATS_TRENDS_V2_PUBLIC=${JSON.stringify(atsV2)};window.ATS_TRENDS_LEDGER_PUBLIC=${JSON.stringify(atsLedger)};</script>`;cache=html.replace('</body>',`${st}\n${patch}\n</body>`);return cache;}
const server=http.createServer(async(req,res)=>{if(req.url==='/_version'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({status:'ok',version:current.version,five_factor:{engine:ff.engineVersion,games:ff.games.length,review:ff.review.status},ats_trends_v2:{games:atsV2.games.length,summary:atsV2.summary,ledgerStatus:atsLedger.weeks?.[0]?.status||'UNKNOWN'},top_board:current.games.slice(0,10).map(g=>({rank:g.rank,game:g.game,lean:g.lean,decision:g.decision,nfelo:g.nfelo.positiveEdge?`${g.nfelo.bestSide} ${g.nfelo.bestEv}%`:'neutral',catherine:g.catherine,amanda:g.amanda})),working_portfolio:current.working_portfolio}));}if(req.url==='/healthz'){const checks={games15:current.games.length===15,nfelo15:current.games.every(g=>g.nfelo),phi:by['LAR @ PHI'].nfelo.bestEv===14,nyg:by['ARI @ NYG'].nfelo.bestEv===2.5,outlay:current.working_portfolio.household_outlay===3800,fourEach:current.working_portfolio.Catherine.length>=4&&current.working_portfolio.Amanda.length>=4,overviewPatch:patch.includes('week4-overview-page-script'),fiveFactor15:ff.games.length===15,fiveFactorFiveEach:ff.games.every(g=>['lineMovement','trends','money','defense','keyNumbers'].every(k=>g.fiveFactor[k])),fiveFactorHandleOnly:ff.games.every(g=>!g.money||g.money.metricType==='handle'),fiveFactorPatch:patch.includes('five-factor-scorecard-script'),atsV2Games15:atsV2.games.length===15,atsV2Ledger15:atsLedger.weeks?.[0]?.games?.length===15,atsV2UiPatch:patch.includes('ats-trends-v2-ui-script')};const ok=Object.values(checks).every(Boolean);res.writeHead(ok?200:503,{'content-type':'application/json'});return res.end(JSON.stringify({status:ok?'ok':'error',version:current.version,checks}));}try{res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(await app());}catch(e){res.writeHead(503);res.end(String(e));}});
server.listen(port,'0.0.0.0',()=>console.log('Command Center '+current.version+' on '+port));
